---
name: Run CI checks

on:
  pull_request:
    types: "**"
    branches: "**"
  pull_request_review:
    types: "**"
    branches: "**"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJSON(github.event) }}"
#   TriggerWorkfows:
#     uses: projectceladon/celadonworkflows/.github/workflows/trigger_ci.yml@v1.0
#     with:
#       EVENT: ${{ toJSON(github.event) }}
